export interface TimezoneOption {
  value: string;
  label: string;
}

export const TIMEZONES: TimezoneOption[] = [
  { value: "America/New_York", label: "(GMT-5) US Eastern — New York" },
  { value: "America/Chicago", label: "(GMT-6) US Central — Chicago" },
  { value: "America/Denver", label: "(GMT-7) US Mountain — Denver" },
  { value: "America/Los_Angeles", label: "(GMT-8) US Pacific — Los Angeles" },
  { value: "Pacific/Honolulu", label: "(GMT-10) US Hawaii — Honolulu" },
  { value: "America/Anchorage", label: "(GMT-9) US Alaska — Anchorage" },
  { value: "America/Toronto", label: "(GMT-5) Canada — Toronto" },
  { value: "America/Vancouver", label: "(GMT-8) Canada — Vancouver" },
  { value: "America/Sao_Paulo", label: "(GMT-3) Brazil — São Paulo" },
  { value: "America/Mexico_City", label: "(GMT-6) Mexico — Mexico City" },
  { value: "America/Bogota", label: "(GMT-5) Colombia — Bogotá" },
  { value: "America/Lima", label: "(GMT-5) Peru — Lima" },
  { value: "Europe/London", label: "(GMT+0) United Kingdom — London" },
  { value: "Europe/Paris", label: "(GMT+1) France — Paris" },
  { value: "Europe/Berlin", label: "(GMT+1) Germany — Berlin" },
  { value: "Europe/Madrid", label: "(GMT+1) Spain — Madrid" },
  { value: "Europe/Rome", label: "(GMT+1) Italy — Rome" },
  { value: "Europe/Amsterdam", label: "(GMT+1) Netherlands — Amsterdam" },
  { value: "Europe/Stockholm", label: "(GMT+1) Sweden — Stockholm" },
  { value: "Europe/Moscow", label: "(GMT+3) Russia — Moscow" },
  { value: "Asia/Dubai", label: "(GMT+4) Gulf — Dubai, Abu Dhabi" },
  { value: "Asia/Singapore", label: "(GMT+8) Singapore" },
  { value: "Asia/Shanghai", label: "(GMT+8) China — Beijing, Shanghai" },
  { value: "Asia/Hong_Kong", label: "(GMT+8) Hong Kong" },
  { value: "Asia/Tokyo", label: "(GMT+9) Japan — Tokyo" },
  { value: "Asia/Seoul", label: "(GMT+9) South Korea — Seoul" },
  { value: "Australia/Sydney", label: "(GMT+10) Australia — Sydney, Melbourne" },
  { value: "Pacific/Auckland", label: "(GMT+12) New Zealand — Auckland" },
  { value: "Africa/Lagos", label: "(GMT+1) Nigeria — Lagos" },
  { value: "Africa/Nairobi", label: "(GMT+3) Kenya — Nairobi" },
  { value: "Africa/Cairo", label: "(GMT+2) Egypt — Cairo" },
  { value: "Africa/Johannesburg", label: "(GMT+2) South Africa — Johannesburg" },
  { value: "UTC", label: "(GMT+0) UTC" },
];

export const EVENT_TYPES: string[] = [
  "Wedding",
  "Party",
  "Baby shower",
  "Conference",
  "Summit",
  "Workshop",
  "Seminar",
  "Webinar",
  "Networking",
  "Meetup",
  "Concert",
  "Exhibition",
  "Trade show",
  "Gala",
  "Award ceremony",
  "Corporate event",
  "Training",
  "Fundraiser",
  "Sports",
  "Other",
];
